all:
	g++ -Wall -I"../LAZEY Library/" -L"../LAZEY Library/" -llazey `sdl2-config --cflags` `sdl2-config --libs` Main.cpp -o Tetris.o -lrt -l bcm2835 -lstdc++ -lboost_system -lboost_thread -D__STDC_LIMIT_MACROS
